### ISSUE TITLE
好奇老哥做到哪一步了

### ISSUE THREAD

**Issue by plusls** [bingling-sama/IMBlocker#1]
(想用

或者实现有什么地方卡着了嘛

**Comment by bingling-sama** [comment]
emmm,这段时间比较忙，而且fabric的开发我也并不是那么熟练，不过我想也快完成了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "plusls"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 中午1:34
收件人: "bingling-sama/IMBlocker"<IMBlocker@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [bingling-sama/IMBlocker] 好奇老哥做到哪一步了 (#1)





 
(想用
 
或者实现有什么地方卡着了嘛

**Comment by plusls** [comment]
因为我看到仓库里面好多奇怪的东西 是不是传错文件了(x

**Comment by bingling-sama** [comment]
IDEA的锅，把我的spring boot项目搞到这个仓库来了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "plusls"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 中午1:38
收件人: "bingling-sama/IMBlocker"<IMBlocker@noreply.github.com&gt;; 
抄送: "冰凌sama"<2082152212@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [bingling-sama/IMBlocker] 好奇老哥做到哪一步了 (#1)





 
因为我看到仓库里面好多奇怪的东西 是不是传错文件了(x

**Comment by plusls** [comment]
🕊🕊🕊🕊
（本来也想移植的 那我摸了

**Comment by bingling-sama** [comment]
哈哈哈哈，之前看到你的移植了，不过进仓库一看居然是个example mod所以我就自己写起来了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "plusls"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 中午1:45
收件人: "bingling-sama/IMBlocker"<IMBlocker@noreply.github.com&gt;; 
抄送: "冰凌sama"<2082152212@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [bingling-sama/IMBlocker] 好奇老哥做到哪一步了 (#1)





 
🕊🕊🕊🕊
 （本来也想移植的 那我摸了

**Comment by plusls** [comment]
你可能记错人了,滑稽,今天有人给我安利了这个mod,想移植结果就看到了issue(x

**Comment by bingling-sama** [comment]
哦..啊这...如果你有能力或许可以参加这个项目？主要是我比较摸




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "plusls"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 中午1:49
收件人: "bingling-sama/IMBlocker"<IMBlocker@noreply.github.com&gt;; 
抄送: "冰凌sama"<2082152212@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [bingling-sama/IMBlocker] 好奇老哥做到哪一步了 (#1)





 
你可能记错人了,滑稽,今天有人给我安利了这个mod,想移植结果就看到了issue(x

**Comment by plusls** [comment]
巧了我也很摸

**Comment by bingling-sama** [comment]
（等我先修好这个仓库再说吧（逃

**Comment by plusls** [comment]
可
